# fly.toml app configuration file generated for backend-production-ogog on 2025-04-21T00:36:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-production-ogog'
primary_region = 'bos'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  max_machines_count = 1
  processes = ['app']
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 0
    soft_limit = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
